No1 = int(input("Enter the first number :"))
No2 = int(input("Enter the second number :"))
No3 = int(input("Enter the thrid number :"))
Greater = lambda No1,No2,No3 : No1 if No1 > No2 and  No1 > No3 else (No2 if No2 > No3 else No3 )
print("Greater number is :",Greater(No1,No2,No3))
